export { getTareas } from "./tareas.js"
export { getUsuarios } from "./usuarios.js"
export { getAlbums } from "./albums.js"
export { getFotos } from "./fotos.js"
export { getPosts } from "./posts.js"
export {getComents} from "./comentarios.js"